# .github/actions/dump-context/action.yml
name: "Dump GitHub Contexts"
description: "Echo out github / job / steps / runner / strategy / matrix contexts"
runs:
  using: "composite"
  steps:
    - name: Dump GitHub context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      shell: bash
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Dump steps context
      shell: bash
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Dump runner context
      shell: bash
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Dump strategy context
      shell: bash
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"

    - name: Dump matrix context
      shell: bash
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Dump environment variables
      shell: bash
      run: |
        echo "GITHUB_REPOSITORY: ${{ github.repository }}"
        echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        echo "GITHUB_EVENT_PATH: ${{ github.event_path }}"
        echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
        echo "GITHUB_REF_TYPE: ${{ github.ref_type }}"
        echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
        echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
        echo "GITHUB_ACTOR: ${{ github.actor }}"
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
        echo "GITHUB_RUN_ID: ${{ github.run_id }}"
        echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
        echo "GITHUB_SERVER_URL: ${{ github.server_url }}"
